---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

#- name: "install dependencies."
#  become: true
#  apt:
#    name: ["curl", "apt-transport-https"]
#    update_cache: yes

- name: Install Docker
  become: true
  shell: |
    cd /home/ubuntu/
    apt install apt-transport-https ca-certificates curl software-properties-common --assume-yes
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    apt-cache policy docker-ce
    apt install docker-ce --assume-yes

- name: Install Minikube
  become: true
  shell: |
    cd /home/ubuntu/
    wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    cp minikube-linux-amd64 /usr/local/bin/minikube
    chmod 755 /usr/local/bin/minikube
    minikube version

- name: Install Kubectl
  become: true
  shell: |
    cd /home/ubuntu/
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl

- name: Add ubuntu user
  shell: |
    cd /home/ubuntu/
    sudo groupadd docker
    sudo usermod -aG docker ubuntu
    newgrp docker
    sudo systemctl restart docker
