---
- name: Start MiniKube
  shell: |
    cd /home/ubuntu/
    minikube start --vm-driver=none

- name: Run Kubernetes
  become: true
  shell: |
    cd /home/ubuntu/
    kubectl run application --image=djarrin/bcrypt-image
    kubectl get pods --all-namespaces

- name: Wait for Kubernetes to Start Up
  pause:
    minutes: 3

- name: Forward Kubernetes Ports
  become: true
  shell: |
    cd /home/ubuntu/
    kubectl port-forward application 8000:80
