---
- name: Start MiniKube
  shell: |
    cd /home/ubuntu/
    sudo minikube start --vm-driver=none
    sudo mv /home/ubuntu/.kube /home/ubuntu/.minikube $HOME
    sudo chown -R $USER $HOME/.kube $HOME/.minikube

- name: Wait for Kubernetes to Start Up
  pause:
    minutes: 1

- name: Run Kubernetes and Forward Ports
  shell: |
    cd /home/ubuntu/
    kubectl run application --image=djarrin/bcrypt-image
    kubectl get pods --all-namespaces
    kubectl port-forward application 8000:80
